### ISSUE TITLE
Minifier Errors need to be reported during build

### ISSUE THREAD

**Issue by johngrogg** [webpack/html-loader#25]
During the build process, if you have an error in your html code (for instance `<div role-"nav">lorem</div>`, the `-` when it should be `=`), instead of reporting the error and stopping the larger webpack build process, the process just hangs.

If it's at all possible, the minifier should error out and report the error to webpack for display to the user.

**Comment by plestik** [comment]
Ran into this as well today. Hard to figure out it was a typo in a template which caused it to hang. +1 for a fix.

**Comment by dmr** [comment]
I'm having this issue, too.

Maybe the html-loader could accept an argument, i.e. ```?timeout=5```.
What do you think?

**Comment by xuyukuan** [comment]
I got the same issue too. +1 for a fix.
