### ISSUE TITLE
How can I copy a video file

### ISSUE THREAD

**Issue by let4be** [webpack/html-loader#28]
loader:
`{
  test: /\.jade$/,
  loader: 'html?attrs[]=img:src!jade-html?doctype=html'
}`

jade:
`video(autoplay,loop,id="bgvid")`
  `source(src="/assets/frames.mp4",type="video/mp4")`

**Comment by let4be** [comment]
Module parse failed: ...
Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

**Comment by rajkissu** [comment]
Add `source:src` to the list of attributes:

```
{ test: /\.jade$/, loader: 'html?attrs[]=img:src&attrs[]source:src!jade-html?doctype=html' }
```

**Comment by d3viant0ne** [comment]
@hemanth - Close me

**Comment by liuliangsir** [comment]
thx~
