### ISSUE TITLE
Strictly match the attribute name

### ISSUE THREAD

**Issue by fenivana** [webpack/html-loader#32]
Vue 1.0 ( https://github.com/yyx990803/vue/wiki/1.0.0-binding-syntax-reference ) uses the following binding syntax, but html-loader will wrongly parse it.
```
<img v-bind:src="foo">
<img :src="foo">
```

**Comment by fenivana** [comment]
Someone has resolved this.
https://github.com/webpack/html-loader/pull/30

**Comment by nervgh** [comment]
Related https://github.com/vuejs/vue/issues/1369#issuecomment-149908997

**Comment by d3viant0ne** [comment]
@hemanth - Close me
