### ISSUE TITLE
minification removes all spaces between tags

### ISSUE THREAD

**Issue by weshardee** [webpack/html-loader#38]
This means potential layout issues between development and production since whitespace is significant in html. Rather than eliminating them entirely, spaces should be collapsed to a single sequential space to better reflect how html is handled by browsers.

**Comment by weshardee** [comment]
At the very least, better documentation should be provided as to which html-minifier options are enabled by default and how to customize them.

**Comment by dizel3d** [comment]
@weshardee, you can use all [html-minifier options](https://www.npmjs.com/package/html-minifier#options-quick-reference). Use `conservativeCollapse` option in query.
I use `{ test: /\.html$/, loader: "html-loader?conservativeCollapse" }` in combination with `new webpack.optimize.UglifyJsPlugin({minimize: true})` in production. It works like you want.

**Comment by weshardee** [comment]
Thanks. I was able to piece that together eventually by reading the code, but it would be nice for others to have this info in the readme, along with the list of default html-minifier options that are enabled.

**Comment by kevinrenskers** [comment]
Now that the defaults have been changed, how can I restore the old behavior? I actually depended on minification removing all spaces between tags.

**Comment by kevinrenskers** [comment]
Never mind.. `html?minimize=true&conservativeCollapse=false`

**Comment by d3viant0ne** [comment]
@hemanth - Issue resolved with #43 Close Me
