### ISSUE TITLE
Why is the default of removeOptionalTags set to true?

### ISSUE THREAD

**Issue by jantimon** [webpack/html-loader#40]
According to http://perfectionkills.com/experimenting-with-html-minifier/#remove_optional_tags this feature might change the behaviour of the result.
This also caused https://github.com/ampedandwired/html-webpack-plugin/issues/128 

Why do you remove HTML, BODY and HEAD?

**Comment by jantimon** [comment]
Thanks @chrisnicola that looks promissing :+1:

**Comment by d3viant0ne** [comment]
@hemanth - Also resolved with #43 Close me
