### ISSUE TITLE
Errror when try to to use with img src

### ISSUE THREAD

**Issue by Ridermansb** [webpack/html-loader#48]
Whats I doing wrong?

**JS Controller**

```javascript
import '../../assets/messaginghub.png';
```

**HTML**
```html
<img src="messaginghub.png" style="margin-bottom: -12px; height: 60px" />
```

**Webpack configuration**
```javascript
{test: /\.png$/i, loader: 'url?mimetype=image/png&name=imgs/[name].[ext]?[hash]', exclude: /node_modules/},
{test: /\.html$/, loader: 'html', exclude: /node_modules/}
```

## Error

    ERROR in ./~/html-loader!./www/components/anon/loginView.html
    Module not found: Error: Cannot resolve 'file' or 'directory' ./\"" in ...\www\components\anon
     @ ./~/html-loader!./www/components/anon/loginView.html 1:1186-1205

![sem titulo](https://cloud.githubusercontent.com/assets/725337/12430003/547039e6-bed4-11e5-89cd-cd4c5f6c8fc8.png)

**Comment by Ridermansb** [comment]
To help a understand this issue.. I [create a project](https://gitlab.com/problems/webpack-html-loader-image).

Just execute.

 1. npm install
 2. npm run bundle 

And a error occur..

    ERROR in ./~/html-loader!./www/components/home/indexView.html
    Module not found: Error: Cannot resolve 'file' or 'directory' ./\"" in    ..\www\components\home
     @ ./~/html-loader!./www/components/home/indexView.html 1:748-767

**Comment by Ridermansb** [comment]
I found the error..  Its need to define a root in loader.

And its not necessary to import the image in controler..just src and html-loader will require the file.

**Comment by tmcgann** [comment]
> I found the error.. Its need to define a root in loader.

For those not sure what that means: https://github.com/webpack/html-loader#root-relative-urls

E.g. `loader: 'html?root=assets/img'` and then `<img src="/image.png">` if you expect your ouput image to be located at `assets/img/image.png`.
