### ISSUE TITLE
Angular template html load by html-loader will error, if webpack use parameter -p

### ISSUE THREAD

**Issue by luoshaohua** [webpack/html-loader#58]
In angular directive, I load template by require('./template.html')
for example:
return {
        restrict: 'AE',
        priority: 1,
        scope: {   gridModel: '=eeTree'},
        template: require('./template.html'),
        link: function ($scope, element, attrs) {}
}
if template.html file contain {{ a<b }}, there will error happen, html-loader or webpack think '<' mean html tag start symbol.
this error only happen by use parameter -p to pack

**Comment by clemgrim** [comment]
you can add the followinf config in your config file:

```
htmlLoader: {
    ignoreCustomFragments: [/\{\{.*?}}/]
},
```

**Comment by d3viant0ne** [comment]
@luoshaohua - Does the addition of `ignoreCustomFragments` resolve your issue? 

If so, can you close this || If not please update with new error info post config change, thanks :)

**Comment by jacqueslareau** [comment]
Had the same problem, ignoreCustomFragments worked for me.

**Comment by d3viant0ne** [comment]
@hemanth - Tag this with something that conveys `A resolution exists in the issue` & it can be closed.
