### ISSUE TITLE
Interpolate Option Outputs Javascript with HTML

### ISSUE THREAD

**Issue by JeremyBYU** [webpack/html-loader#59]
I'm using the interpolate option, `var mytemplate = require('html?interpolate!./mytemplate.html')`, to include 'partials' in my html file

```
mytemplate.html

<div>
${require(./partials/mypartial.html)}
</div>

```
```
partials/mypartial.html

In a partial
```

The partial get appropriately loaded but the resulting html string (mytemplate) has the html wrapped in module.exports("HTML_FILE_HERE");

The final result would place the string `'module.exports("<div>In a partial</div>")'` in the variable mytemplate.  I want it to be simply the html, which is the way it isually is if I don't have the option interpolate option turned on for the require.

What am I doing wrong, or is this a bug?

**Comment by andersstorhaug** [comment]
For anyone stumbling on this in the future, try:
```
<div>
${require('!raw!./partials/mypartial.html')}
</div>
```

The leading `!` is to override configured loaders.

**Comment by nicefan** [comment]
this not auto replace IMG src path. raw

**Comment by ericrav** [comment]
this is hacky, but I used `use: ['file-loader?name=[name].[ext]', 'extract-loader', 'html-loader', 'extract-loader', 'html-loader?interpolate']` in my webpack config, so all partials would get interpolated first, then second html-loader pass would fix img srcs
