### ISSUE TITLE
Point out about extract-loader to deal with file-loader in README

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [webpack/html-loader#62]
I would like to make a pull request to improve the README to mention [extract-loader](https://github.com/peerigon/extract-loader) to deal with file-loader, because it seems a scenario some people requested (dealing with angular), is _not documented_ on the web and can save quite some time. Is it fine or there are some specific guidelines to avoid that?

**Comment by hemanth** [comment]
> I would like to make a pull request to improve the README

Please do so, if it looks all good after the review it shall go in, thanks!

**Comment by Fire-Dragon-DoL** [comment]
@hemanth provided a PR! ;)
