### ISSUE TITLE
Travis execution inline with webpack/webpack

### ISSUE THREAD

**Issue by d3viant0ne** [webpack/html-loader#69]
**Bring html-loaders travis execution inline with webpack core**
- [x] Add linting
- [x] Add coverage generation / reporting via codecov.io
- [x] Status badges in readme ( Readme template coming from @michael-ciniawsky )

**Comment by d3viant0ne** [comment]
@hemanth - https://codecov.io/gh/webpack/html-loader requires write access to enable initially.

**Comment by hemanth** [comment]
@d3viant0ne I have the write access.

*  #74 is breaking the build right? 

* #66 looks good.

* #70 is merged!

* Checking #55, that would need a version bump, post merge.

* Rest which were apt to be merged have been merged.

Good going!

**Comment by d3viant0ne** [comment]
@hemanth - The build was broken in #master as of yesterday when I first forked. 4 failing tests but there was no travis feedback on PRs so evidently it went undetected.

Much like the linting fixes, I was going to fix the tests in the PR that updates the Travis execution #74  so we can get proper validation in pull requests going forward.

Just to be very clear, every PR open right now has 4 failing tests, as does the master branch as of yesterday when I first looked. There is no travis feedback in the PRs, which is why they are green.

#66 for instance ..
<img width="885" alt="screen shot 2016-07-24 at 11 43 59 am" src="https://cloud.githubusercontent.com/assets/8420490/17085050/0b7ea4b8-5194-11e6-8221-034cdc18652b.png">

Though if you go look at the builds for master in Travis ..

<img width="1409" alt="screen shot 2016-07-24 at 11 45 56 am" src="https://cloud.githubusercontent.com/assets/8420490/17085057/42b22ba8-5194-11e6-8387-3f84eec75c6e.png">
